# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:

  github-npm: # Define access for a private registry
    type: npm-registry
    url: https://npm.pkg.github.com
    username: patuser
    password: ${{secrets.DEPENDABOT_PKGS_R_PAT}}

updates:

  - package-ecosystem: docker
    directory: /docker/image-chromium-npm/
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    target-branch: dev

  - package-ecosystem: docker
    directory: /docker/image-dev/
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    target-branch: dev

  - package-ecosystem: npm # See documentation for possible values
    directory: /myapp/ # Location of package manifests
    registries:
      - github-npm
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    target-branch: dev

  - package-ecosystem: npm # See documentation for possible values
    directory: /mylib/ # Location of package manifests
    registries:
      - github-npm
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    target-branch: dev
