name: Docker images

on:
  push:
    branches-ignore: ["**"]
    tag:
      - img/

jobs:
  images:
    name: Build images
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/img/') || startsWith(github.ref, 'refs/heads/')}}
    env:
      IMAGE_PUSH: ${{ startsWith(github.ref, 'refs/tags/img/') }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Calculate environments
        run: |
          cat ./docker/ci.env >> $GITHUB_ENV
          echo IMAGE_REPO=docker.pkg.github.com/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_TAG=$(./.github/workflows/docker-tag.sh ${{ github.ref }}) >> $GITHUB_ENV

      - name: Calculate images full name
        run: |
          echo CHROMIUM_NPM_IMAGE=${{env.IMAGE_REPO}}/ttp-chromium-npm:${{ env.IMAGE_TAG }} >> $GITHUB_ENV
          echo DEV_IMAGE=${{env.IMAGE_REPO}}/ttp-dev:${{ env.IMAGE_TAG }} >> $GITHUB_ENV

      - name: Show docker and docker-compose versions
        run: |
          docker --version
          docker-compose --version

      - name: Login to GitHub Packages Docker Registry
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build chromium-npm image
        run: |
          docker build \
              --rm \
              -f docker/image-chromium-npm/Dockerfile \
              -t ${{env.CHROMIUM_NPM_IMAGE}} \
              docker/image-chromium-npm

      - name: Show layers
        run: |
          docker history --no-trunc ${{env.CHROMIUM_NPM_IMAGE}}

      - name: Push chromium-npm image
        if: ${{ env.IMAGE_PUSH == 'true' }}
        run: |
          docker push ${{env.CHROMIUM_NPM_IMAGE}}

      - name: Build dev image
        run: |
          docker build \
              --rm \
              -f docker/image-dev/Dockerfile \
              -t ${{env.DEV_IMAGE}} \
              --build-arg BASE_IMAGE=${{env.CHROMIUM_NPM_IMAGE}} \
              docker/image-dev/

      - name: Show layers
        run: |
          docker history --no-trunc ${{env.DEV_IMAGE}}

      - name: Push dev image
        if: ${{ env.IMAGE_PUSH == 'true' }}
        run: |
          docker push ${{env.DEV_IMAGE}}
